package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/takanoriyanagitani/go-detect-language-ql/graph/model"
)

// DetectLanguage is the resolver for the detectLanguage field.
func (r *queryResolver) DetectLanguage(ctx context.Context, input *model.DetectLanguageInput) (*model.DetectLanguageOutput, error) {
	return r.Resolver.DetectLanguage(ctx, input)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
