// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Input for the language detection query.
type DetectLanguageInput struct {
	// A unique identifier for the request.
	RequestID string `json:"requestID"`
	// The text to be analyzed.
	Text string `json:"text"`
	// The minimum confidence threshold. Languages below this will be excluded.
	MinConfidence *float64 `json:"minConfidence,omitempty"`
	// The maximum number of languages to return.
	MaxLanguages *int64 `json:"maxLanguages,omitempty"`
}

// The output of the language detection query.
type DetectLanguageOutput struct {
	// The unique identifier for the request.
	RequestID string `json:"requestID"`
	// A list of detected languages that meet the filtering criteria.
	Detected []*DetectedLanguage `json:"detected"`
	// Statistics about the detection process.
	Stats *Stats `json:"stats"`
}

// Represents a single detected language and its confidence score.
type DetectedLanguage struct {
	// The ISO 639-1 code for the language (e.g., 'en').
	Iso639i string `json:"iso639i"`
	// The ISO 639-3 code for the language (e.g., 'eng').
	Iso639iii string `json:"iso639iii"`
	// The display name of the language (e.g., 'English').
	Language string `json:"language"`
	// The confidence score of the detection (0.0 to 1.0).
	Confidence float64 `json:"confidence"`
}

type Query struct {
}

// Provides statistics about the detection process.
type Stats struct {
	// The total number of languages the detector was configured to check against.
	TotalSupportedLanguages int64 `json:"totalSupportedLanguages"`
	// The number of languages found in the text before any filtering.
	DetectedLanguages int64 `json:"detectedLanguages"`
	// The number of languages filtered out due to low confidence or the maxLanguages limit.
	SkippedLanguages int64 `json:"skippedLanguages"`
}
